// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1nKRhCYn-q-KsegkerzJxgpL8tZhQCks',
    appId: '1:270279405346:web:4cf5b2d46e6c29515e3f7b',
    messagingSenderId: '270279405346',
    projectId: 'final-year-project---comlink',
    authDomain: 'final-year-project---comlink.firebaseapp.com',
    storageBucket: 'final-year-project---comlink.firebasestorage.app',
    measurementId: 'G-X5R261LDYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBotnpxCoMi6W5F1be7gG0x-v1DzbcMIoU',
    appId: '1:270279405346:android:cd820b06aca1d6255e3f7b',
    messagingSenderId: '270279405346',
    projectId: 'final-year-project---comlink',
    storageBucket: 'final-year-project---comlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnevdF86wWKnAhvosnF2Oxr1p-8PlDa0',
    appId: '1:270279405346:ios:8bec6d62bfb3c91d5e3f7b',
    messagingSenderId: '270279405346',
    projectId: 'final-year-project---comlink',
    storageBucket: 'final-year-project---comlink.firebasestorage.app',
    iosBundleId: 'com.example.comlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnevdF86wWKnAhvosnF2Oxr1p-8PlDa0',
    appId: '1:270279405346:ios:8bec6d62bfb3c91d5e3f7b',
    messagingSenderId: '270279405346',
    projectId: 'final-year-project---comlink',
    storageBucket: 'final-year-project---comlink.firebasestorage.app',
    iosBundleId: 'com.example.comlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1nKRhCYn-q-KsegkerzJxgpL8tZhQCks',
    appId: '1:270279405346:web:1236a64121da41875e3f7b',
    messagingSenderId: '270279405346',
    projectId: 'final-year-project---comlink',
    authDomain: 'final-year-project---comlink.firebaseapp.com',
    storageBucket: 'final-year-project---comlink.firebasestorage.app',
    measurementId: 'G-D6HSSF0392',
  );
}
